version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Prague"
    groups:
      actions:
        patterns:
          - "*"
    reviewers:
      - "jan-kubica"
      - "pavelm10"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/pairlegal-documentation"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Prague"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      docusaurus:
        patterns:
          - "@docusaurus/*"
    labels:
      - "dependencies"
    versioning-strategy: increase-if-necessary
    reviewers:
      - "jan-kubica"
      - "pavelm10"
