version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Prague"
    groups:
      actions:
        patterns:
          - "*"
    reviewers:
      - "jan-kubica"
      - "pavelm10"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Prague"
    groups:
      all-non-rooka:
        patterns:
          - "*"
    labels:
      - "dependencies"
    versioning-strategy: increase-if-necessary
    reviewers:
      - "jan-kubica"
      - "pavelm10"
