name: "\U0001F41B Bug Report"
description: Submit a bug report
title: "bug: "
labels: ["🐞 bug"]
body:
  - type: textarea
    id: reproduction
    validations:
      required: false
    attributes:
      label: Reproduction
      description: |
        Describe what is wrong, ideally with a failing test case.

      placeholder: |
        Steps to reproduce the behavior:

          1.
          2.
          3.

  - type: textarea
    id: expected-behavior
    validations:
      required: false
    attributes:
      label: Expected behavior
      description: "A short description of what you would expect to happen."
