# This epic template

name: "\u26A1 Epic"
description: Epic
title: "epic: "
labels: ["⚡ epic"]
body:
  - type: textarea
    id: epic-description
    validations:
      required: true
    attributes:
      label: Epic description
      description: |
        A description of the epic.

  - type: textarea
    id: linked-issues
    validations:
      required: true
    attributes:
      label: Linked Issues
      description: |
        TODO list of issues that are part of this epic.
