[tool.poetry]
name = "usefulness-api"
version = "0.1.0"
description = ""
authors = ["Sven Spehr <spehr.sv@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.33"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
